name: debug-on-windows
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: Upload output
      uses: actions/upload-artifact@v3
      with:
        name: output
        path: output
        if-no-files-found: error
