# This is a basic workflow to help you get started with Actions

name: build-project

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up Python 
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies and Pyinstaller
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          mkdir output
      - name: Pack the Project
        run: pyinstaller -F -i icon.ico CDNDrive/__main__.py --distpath output -n cdrive
      - name: Upload Project
        uses: actions/upload-artifact@v3
        with:
          name: cdrive-${{ matrix.os }}
          path: output
          if-no-files-found: error
